// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAFKXf6avchGWrwxJeM0hF8SaMqvABB3s',
    appId: '1:631120006706:web:7308aefa16b7adb4d4762b',
    messagingSenderId: '631120006706',
    projectId: 'spofify01',
    authDomain: 'spofify01.firebaseapp.com',
    storageBucket: 'spofify01.appspot.com',
    measurementId: 'G-WM6ZPXRCT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQ2EpMf0oRwPLJsUopQkHmHHOa7dHMYg',
    appId: '1:631120006706:android:637a36c914905ba9d4762b',
    messagingSenderId: '631120006706',
    projectId: 'spofify01',
    storageBucket: 'spofify01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDxaI2AGccGGMT3VTfLU1S0YVZj4jUa8',
    appId: '1:631120006706:ios:222807e80819cc46d4762b',
    messagingSenderId: '631120006706',
    projectId: 'spofify01',
    storageBucket: 'spofify01.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrDxaI2AGccGGMT3VTfLU1S0YVZj4jUa8',
    appId: '1:631120006706:ios:222807e80819cc46d4762b',
    messagingSenderId: '631120006706',
    projectId: 'spofify01',
    storageBucket: 'spofify01.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAFKXf6avchGWrwxJeM0hF8SaMqvABB3s',
    appId: '1:631120006706:web:9c098c00dd8e812fd4762b',
    messagingSenderId: '631120006706',
    projectId: 'spofify01',
    authDomain: 'spofify01.firebaseapp.com',
    storageBucket: 'spofify01.appspot.com',
    measurementId: 'G-7DSEGLV83Y',
  );
}
